[package]
name = "sample"
version = "0.1.0"
authors = ["kennytm <kennytm@gmail.com>"]
description = "Example static library project built for iOS and Android"

[dependencies]
regex = "0.1.73"
jni-sys = "0.1.0"

[lib]
name = "sample"
crate-type = ["staticlib", "cdylib"]
